# Dockerfile.frontend
FROM nginx:alpine

# Remueve la configuración por defecto de Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia la configuración personalizada de Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copia los archivos estáticos desde 'app/static/' a la raíz de Nginx
COPY app/static/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]